name: resomy_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  table_calendar: ^3.0.1
  google_fonts: ^2.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/svg/
    - assets/images/png/
  uses-material-design: true





